language: node_js
node_js:
  - "node"

services:
  - postgresql

addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4

cache:
  npm: true
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm ci

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - SLACKIFY_SERVICE=slackify-service-private ./scripts/build.sh
  - npx lerna run migrate:up --scope slackify-prisma
  - npx lerna run seed --scope slackify-prisma
  - npx lerna run start --scope slackify-service-private &

script:
  - SLACKIFY_SERVICE=slackify-frontend ./scripts/build.sh
  - npx lerna run start --scope slackify-frontend &
  - npx lerna run cypress --scope slackify-frontend
