language: node_js
node_js:
  - "node"

addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4

cache:
  npm: true
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm ci

before_script:
  - SLACKIFY_SERVICE=slackify-service-private ./scripts/build.sh
  - cd packages/service-private && npm start &

script:
  - SLACKIFY_SERVICE=slackify-frontend ./scripts/build.sh
  - cd packages/frontend && npm start &
  - cd packages/frontend && npm run cypress
