language: node_js
node_js:
  - "node"

addons:
  chrome: stable
  apt:
    packages: -libgconf-2-4

cache:
  npm: true
  directories:
    - ~/.npm
    - ./node_modules
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

install:
  - npm ci

matrix:
  include:
    - env: TARGET=frontend
    - env: TARGET=prisma
    - env: TARGET=service-private
    - env: TARGET=service-public
    - env: TARGET=service-slack

script: if .travis/build-condition.sh $TRAVIS_COMMIT_RANGE $TARGET; then echo "$TARGET is being built" && cd $TARGET && npm install && npm run ci; else echo "$TARGET is NOT being built"; fi
