version: '2.4'

services:
  db:
    image: postgres:12.1
    container_name: slackify_db
    ports:
      - '5432:5432'
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
      - ./.db/initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
    environment:
      POSTGRES_PASSWORD: password
